[keyboard]
name = "WISH60-BLE-RMK"
product_name = "WISH60-BLE-RMK"
vendor_id  = 0xBA02
product_id = 0x0005
manufacturer = "BARAM"
chip = "nrf52840"

[matrix]
# Row and col pins are mandatory
col_pins = ["P0_13", "P0_14", "P0_15", "P0_16", "P1_02"]
row_pins = ["P1_11", "P1_12", "P1_13", "P1_14", "P1_15", "P0_03", "P0_17", "P0_21", "P0_20", "P0_23", "P0_22", "P1_00", "P0_24", "P0_25", "P1_10"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true


[layout]
rows = 15
cols = 5
layers = 8
matrix_map = """
(0,0) (1,0) (2,0) (3,0) (4,0) (5,0) (6,0) (7,0) (8,0) (9,0) (10,0) (11,0) (12,0)        (14,0) 
(0,1) (1,1) (2,1) (3,1) (4,1) (5,1) (6,1) (7,1) (8,1) (9,1) (10,1) (11,1) (12,1) (13,1)
(0,2) (1,2) (2,2) (3,2) (4,2) (5,2) (6,2) (7,2) (8,2) (9,2) (10,2) (11,2)        (13,2) 
(0,3) (1,3) (2,3) (3,3) (4,3) (5,3) (6,3) (7,3) (8,3) (9,3) (10,3)        (12,3) 
(0,4) (1,4) (2,4)                   (6,4)             (9,4)        (11,4) (12,4) (13,4) 
"""

[[layer]]
name = "0"
keys = """
grv  1 2 3 4 5 6 7 8    9   0    mins eql       bspc
Tab  Q W E R T Y U I    O   P    lbrc rbrc bsls
caps A S D F G H J K    L   scln quot      ent
lsft Z X C V B N M comm Dot slsh      rsft
lctl lwin l_alt  spc    r_alt    MO(1) _ rctl
"""

[[layer]]
name = "1"
keys = """
_ F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 del
_ User0 User1 User2 User3 User4 User5 User6 _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ 
_ _ _ _ _ _ _ _ _ _ _ _ 
_ _ _ _ _ _ _ _ 

"""

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
capslock.pin = "P0_05"
capslock.low_active = false

[storage]
# Storage feature is enabled by default
# enabled = false
clear_storage = true


[ble]
enabled = true
# vddh has an internal voltage divider
battery_adc_pin = "vddh"


[host]
# Unlock combination: simultaneous press of specified keys
# Format: [[row, col], [row, col], ...]
unlock_keys = [[0, 0], [0, 1]]  # Keys at (row=0,col=0) and (row=0,col=1)


[rmk]
combo_max_num = 128 
fork_max_num = 16
