[keyboard]
name = "WISH60-BLE-RMK"
product_name = "WISH60-BLE-RMK"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "baram"
chip = "nrf52840"

[matrix]
# Row and col pins are mandatory
col_pins = ["P0_13", "P0_14", "P0_15", "P0_16", "P1_02"]
row_pins = ["P1_11", "P1_12", "P1_13", "P1_14", "P1_15", "P0_03", "P0_17", "P0_21", "P0_20", "P0_23", "P0_22", "P1_00", "P0_24", "P0_25", "P1_10"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true


[layout]
rows = 15
cols = 5
layers = 8

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
capslock.pin = "P0_05"
capslock.low_active = false

[storage]
# Storage feature is enabled by default
# enabled = false
# clear_storage = true


[ble]
enabled = true
# vddh has an internal voltage divider
battery_adc_pin = "vddh"


[host]
# Unlock combination: simultaneous press of specified keys
# Format: [[row, col], [row, col], ...]
unlock_keys = [[0, 0], [0, 1]]  # Keys at (row=0,col=0) and (row=0,col=1)


[rmk]
combo_max_num = 128 
fork_max_num = 16
