[keyboard]
name = "WISH60-BLE-RMK"
product_name = "WISH60-BLE-RMK"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "baram"
chip = "nrf52840"

[matrix]
# Row and col pins are mandatory
row_pins = ["P0_13", "P0_14", "P0_15", "P0_16", "P1_02"]
col_pins = ["P1_11", "P1_12", "P1_13", "P1_14", "P1_15", "P0_03", "P0_17", "P0_21", "P0_20", "P0_23", "P0_22", "P1_00", "P0_24", "P0_25", "P1_10"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
row2col = true

[layout]
rows = 5
cols = 15
layers = 8
matrix_map = """
(0,0) (0,1) (0,2) (0,3)
(1,0) (1,1) (1,2) (1,3)
(2,0) (2,1) (2,2)
(3,0) (3,1) (3,2) (3,3)
    (4,0)    (4,1)
"""
[[layer]]
name = "base_layer"
keys = """
NumLock KpSlash KpAsterisk KpMinus
Kp7     Kp8     Kp9        KpPlus
Kp4     Kp5     Kp6
Kp1     Kp2     Kp3        Enter
    Kp0         KpDot
"""

[[layer]]
name = "second_layer"
keys = """
TD(1)  TO(0)        WM(W,LShift)         No
DF(0)  LT(1, Space) LM(0, LShift | RGui) 
OSL(0) OSM(LAlt)    TH(Kp1, Kp2)        SHIFTED(Kp2)
    @my_copy        @my_paste
"""

[aliases]
my_copy = "WM(C, LCtrl)"
my_paste = "WM(V, LCtrl)"

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
capslock.pin = "P0_05"
capslock.low_active = false

[storage]
# Storage feature is enabled by default
# enabled = false
# clear_storage = true


[ble]
enabled = true
# vddh has an internal voltage divider
battery_adc_pin = "vddh"


[rmk]
combo_max_num = 128 
fork_max_num = 16
